# =============== Solving Futures ===============
extra_resources: 'PortfolioFiles/input_data/extra_resources.xlsx'
futures_file: 'PortfolioFiles/sample_of_futures/default_3_02.01.2025.csv'
n_evaluate: 'all'

results_output_string: "results_default"
results_output_path: 'PortfolioFiles/results_from_modelling/'
results_output_type: "csv"

# =============== Creating futures sample ===============
input_file_path: "PortfolioFiles/input_data/All data.xlsx" # NOTE: 'step' or 'size' no longer require different input files
n_sample: 3000 # Integer >0
sampling_method: 'size' # step or size
future_zero: True # True or False
output_string: "default_3"
output_path: "PortfolioFiles/sample_of_futures/"
output_type: "csv" # xlsx or csv

# 'size': if sampling size (number of values a parameter can take) is given:
sampling_size:
  size:
    Energy: 4
    Land: 3
    ER: 10
    Ymax: 10
    GeoSt: 5
  not_sampled:
    OPEX: "-"
    SCref: "-"
    Yref: "-"
    Xmax: "-"
  exceptions:
    CDRRequired: 100000000000 #1e11 tCO2
    EnergyL: 5 # years
    LandL: 100000000 #1e8 Mha

# 'step': if sampling step (step between values of a parameter) is given:
sampling_step:
  step:
    Energy: 0.5 # GJ/tCO2
    Land: 0.01 # ha/tCO2
    ER: 0.01 # percentage
    Ymax: 500000000 # 5e8 
    GeoSt: 4000000000 #4e9 GtCO2/yr
    CDRRequired: 100000000000 #1e11 tCO2
    EnergyL: 5 # years
    LandL: 100000000 #1e8 ha
  not_sampled:
    OPEX: "-"
    SCref: "-"
    Yref: "-"
    Xmax: "-"