input_file_path: "PortfolioFiles/Portfolio_Files_Latest/All data Step size.xlsx"
n_sample: 5 # Integer >0
sampling_method: 'step' # step or size
future_zero: False # True or False
output_string: "revision_one"
output_path: "PortfolioFiles/sample_of_futures/"
output_type: "csv" # xlsx or csv