name: cdr_portfolio_model_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>19
  - matplotlib
  - numpy
  - pandas
  - pyomo
  - scipy
  - tqdm
  - pooch>=1.8
  - pyam>=2.3
  - pip:
    - scikit-learn
    - graphviz
