name: cdr_portfolio_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>19
  - matplotlib
  - numpy
  - pandas
  - pyomo
  - scipy
  - tqdm
  - pooch>=1.8
  - pyam>=2.3
  - pip:
    - scikit-learn
    - graphviz
    - pyDOE2
    - seaborn 
    - pyomo
    - plotly==5.24.1 # https://pypi.org/project/plotly/
    - PyYAML 
    - openpyxl
    - cmcrameri
    - ema_workbench
